import puppeteer from 'puppeteer-core';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const OUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../shots');
const b = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox', '--force-device-scale-factor=2'] });
const p = await b.newPage();
await p.setViewport({ width: 560, height: 1010, deviceScaleFactor: 2 });
await p.setCacheEnabled(false);
await p.goto('http://127.0.0.1:5180/?t=' + Date.now(), { waitUntil: 'networkidle0' });
await p.waitForFunction('window.__game');
await p.evaluate(() => window.__game.openShop());
await new Promise((r) => setTimeout(r, 80));
await p.screenshot({ path: path.join(OUT, 'peach-shop-bottom.png'), clip: { x: 0, y: 790, width: 560, height: 210 } });
await b.close();
console.log('ok');
