/** 英文配置键 → 中文说明（DevTools 表单 / Diff 展示） */
export const PARAM_ZH: Record<string, string> = {
  // ECONOMY
  INITIAL_PEACH: '开局蟠桃',
  PEACH_PER_KILL: '普通怪掉桃',
  PEACH_PER_BLEED: '唐僧掉血补偿桃',
  PEACH_PER_ELITE: '精英掉桃',
  PEACH_PER_MINI_BOSS: '小 Boss 掉桃',
  PEACH_PER_BOSS: '妖王掉桃',
  TANGSENG_INITIAL_HP: '唐僧初始血量',
  ENDLESS_TANGSENG_INITIAL_HP: '唐僧初始血量（无尽模式）',
  TANGSENG_MAX_HP: '唐僧血量上限（最多 9 滴）',
  MAX_PEACH: '蟠桃数量上限（防溢出）',
  MONSTER_BASE: '【未接线】参考怪数基数（实战硬编码 10+n−1）',
  PEACH_COST_BASE: '【未接线】参考抽卡成本基数（实战用 summonCostStart）',
  PEACH_COST_STEP: '【未接线】参考抽卡成本递增（实战用 summonCostStep）',
  REMAINING_INTERCEPT: '【未接线】参考剩余桃曲线截距',

  // BOARD_POWER
  PRESSURE_RATIO: '承压比（恒定，全波次一致）',
  PRESSURE_WINDOW_SEC: '承压窗口（秒）',
  PRESSURE_FROM_WAVE: '承压起始波次',
  ENTRANCE_ZONE_LEN: '门口路段长度（格）',
  SPAWN_INTERVAL_MIN: 'BOARD_POWER 默认出怪间隔下限（秒；实战读 TUNING.spawnIntervalMin）',
  GATE_WIPE_HP_RATIO: '门口秒杀血量比',
  SPAWN_DIST_JITTER: '同批出怪沿路抖动（格）',
  SPAWN_BATCH_CAP_MAX: '单次出怪批次上限',
  MONSTER_HP_FROM_WAVE: '按武器攻击缩放血量起始波次',
  MONSTER_HP_KILL_SEC: '单怪参考击杀时长（秒）',

  // PLACE_TIMING
  digDur: '挖坑动画时长（秒）',
  dropDur: 'AI 落子动画时长（秒）',
  dragDur: '一键布阵拖拽时长（秒）',
  staggerMin: '连续落子最短间隔（秒）',
  staggerMax: '连续落子最长间隔（秒）',

  // PEACH_TREE
  intervals: '各级产桃间隔（秒）',
  maxLevel: '桃树最高等级',
  plantInterval: '自动种树间隔（秒）',

  // AI_TIMING
  weaponAdjustMin: 'AI 兵器调位间隔下限',
  weaponAdjustMax: 'AI 兵器调位间隔上限',
  partnerAdjustMin: 'AI 配对调位间隔下限',
  partnerAdjustMax: 'AI 配对调位间隔上限',
  adjustFastScale: 'AI 快放模式间隔缩放倍率',

  // GENERAL_TUNING
  CRIT_MULT: '暴击倍率',
  BOND_ATK_BONUS: '羁绊全队攻击加成',

  // WEAPON_TUNING
  rangeStep: '神兵每阶范围加成（格）',
  pctPerTier: '神兵每阶攻/速比例',
  battleFragmentEligibleChance: '本局可掉碎片预排概率',
  heroAttackFragmentChance: '英雄攻击触发碎片概率',

  // TUNING · 怪物 / 系统 / 攻击（节选常用）
  monsterSpd: '怪物移速（格/秒）',
  dangerRemaining: '危险提示剩余格数',
  monsterHpBase: '怪物血量基数',
  monsterHpStep: '怪物血量每波递增',
  monsterHpEarlyFixed: '前几波固定血量表',
  monsterHpNoDiffTo: '小怪HP固定公式截止波',
  monsterHpRampMulByCycle: '小怪HP爬坡倍数(按圈递增)',
  bossFirstSegLo: '首段妖王波下界',
  bossFirstSegHi: '首段妖王波上界',
  bossFirstSegMin: '首段妖王波最少',
  bossFirstSegMax: '首段妖王波最多',
  bossSegMin: '后续每段妖王波最少',
  bossSegMax: '后续每段妖王波最多',
  bossHpMul: '妖王血量倍率（后期）',
  bossHpMulEarly: '妖王血量倍率（前期）',
  bossSpdMul: '妖王移速倍率',
  bossHpRampWaves: '妖王血量爬升波跨度',
  bossEscortMin: '妖王护卫最少',
  bossEscortMax: '妖王护卫最多',
  bossEscortHpShare: '护卫分血比例',
  bossEscortSpacing: '护卫沿路间距',
  cavalryFromWave: '骑兵波起始波次',
  cavalryWaveChance: '骑兵波概率',
  cavalryRatioRampLoWave: '骑兵占比爬升起始波',
  cavalryRatioRampHiWave: '骑兵占比爬升结束波',
  cavalryRatioRampStart: '骑兵占比爬升下限',
  cavalryRatioRampEnd: '骑兵占比爬升上限',
  cavalryRatioLateLo: '后期骑兵占比随机下限',
  cavalryRatioLateHi: '后期骑兵占比随机上限',
  cavalrySpdMul: '骑兵移速倍率',
  cavalryHpMul: '骑兵血量倍率',
  spawnInterval: '出怪基础间隔（秒）',
  spawnIntervalMin: '实战出怪间隔下限（秒）',
  summonCostStart: '首次征兵成本（实战）',
  summonCostStep: '征兵成本递增（实战）',
  aiOffensiveActiveMinDist: 'AI 攻击主动最短走过格数',
  aiOffensiveActiveDelayMax: 'AI 攻击主动随机延迟上限（秒）',
  shovelDrawChance: '铲子出现概率',
  shovelPityAfter: '铲子保底次数',
  wordDrawChance: '字牌出现概率',
  wordPityAfter: '字牌保底次数',
  pairPityAfter: '半对保底次数',
  earlyWordCapWave: '前期字牌上限波次',
  earlyWordCap: '前期字牌上限个数',
  earlyWordGuaranteeWave: '前期字牌保底波次',
  earlyWordGuarantee: '前期字牌保底个数',
  earlyShovelWave: '前期铲子配额波次',
  earlyShovelMin: '前期铲子下限',
  earlyShovelMax: '前期铲子上限',
  summonMaxPerKey: '单次同 key 上限',
  summonMaxPerKeyAllOpen: '全开后同 key 上限',
  traySize: '候选区容量',
  initialShovels: '开局铲子数',
  initialOpenSlots: '初始阵位数',
  wavesPerCycle: '每圈波数(对战/无尽共用)',
  cycleStrengthMul: '每圈强度倍率(对战/无尽共用)',
  eliteFromWave: '精英出现起始波',
  eliteChance: '精英概率',
  eliteMinGap: '精英最小间隔只数',
  skillRadius: '妖王/精英技能半径（格）',
  skillTargetMin: '妖王/精英技能最少命中兵器',
  skillTargetMax: '妖王/精英技能最多命中兵器',
  skillInterval: '妖王/精英施法CD间隔（秒）',
  skillFirstDelay: '妖王/精英首次施法延迟（秒）',
  stunDur: '定身时长（白骨岭妖王/精英）',
  slowDur: '迟滞时长（流沙河妖王/精英·霜魄）',
  slowCooldownMul: '迟滞期冷却倍率',
  weakenDur: '弱身时长（火焰山妖王/精英·蚀甲）',
  weakenAtkMul: '弱身期攻击倍率',
  webbindDur: '缠丝时长（盘丝洞妖王/精英）',
  webbindRangeCut: '缠丝射程削减',
  debuffImmuneDur: '同类减益免疫时长',
  miniBossFromWave: '小 Boss 起始波',
  miniBossChance: '小 Boss 概率',
  miniBossHpMul: '小 Boss 血量倍率',
  miniBossSpdMul: '小 Boss 移速倍率',
  miniBossSpdMulSlow: '小 Boss 移速(霜魄/撼地/血泉)',
  miniBossSpdMulFast: '小 Boss 移速(疾风)',
  miniBossRadius: '小 Boss 光环半径',
  miniBossInterval: '小 Boss 施法间隔',
  miniBossFirstDelay: '小 Boss 首次施法延迟',
  miniBossStealRadius: '黄狮精卷走半径',
  miniBossStealDelayMin: '黄狮精首次触发最短延时',
  miniBossStealDelayMax: '黄狮精首次触发最长延时',
  miniBossStealFlashDur: '黄狮精卷走闪烁时长',
  eliteHpMul: '精英血量倍率',
  knockdownDur: '倒下时长（撼地）',
  hasteDur: '疾风时长',
  hasteSpdMul: '疾风移速倍率',
  healPct: '血泉回复比例',
  aiClearRadius: '清场/紧箍半径',
  palmPushCells: '神掌击退格数',
  meteorDmgMul: '陨石伤害倍率',
  meteorRadius: '陨石半径',
  meteorPassiveDmgMul: '被动陨石倍率',
  jingguDmgMul: '紧箍咒伤害倍率',
  bombDmgMul: '炸药伤害倍率',
  bombExplodeRadius: '炸药爆炸半径',
  bombContactRadius: '炸药触发半径',
  atkBuffMul: '仙丹攻击倍率',
  frqBuffMul: '风火轮攻速倍率',
  freezeStunDur: '冰封定身时长',
  wuxingAdvMul: '五行克制伤害倍率（克方）',
  wuxingDisMul: '五行被克伤害倍率（被克方）',
  CC_TIME_BONUS: '每秒定身额外伤害系数（定越久塔白打越多）',
  PUSH_CELL_BONUS: '每格击退额外伤害系数',
  SLOW_TIME_BONUS: '每秒减速额外伤害系数（减速半效）',
  heroStunDurMain: '满5定身时长',
  heroStunDurTransit: '满3定身时长',
  heroKnockPushMain: '满5击退格数',
  heroKnockPushTransit: '满3击退格数',
  heroStunDmgMul: '定身附带伤害倍率',
  heroChargeStunDmgMul: '冲撞定身伤害倍率',
  heroKnockDmgMul: '击退附带伤害倍率',
  heroSlowDmgMulMain: '满5减速附带伤害',
  heroSlowDmgMulTransit: '满3减速附带伤害',
  heroSlowDur: '英雄减速时长',
  heroHealSlowDur: '回复减速时长',
  heroBurnHitMul: '灼烧瞬时倍率',
  heroBurnDpsMul: '灼烧每秒倍率',
  heroBurnDur: '灼烧持续',
  heroBuffAtkMulMain: '老君攻击增益倍率',
  heroBuffAtkMulTransit: '丹君攻击增益倍率',
  heroBuffDurMain: '老君增益时长',
  heroBuffDurTransit: '丹君增益时长',
  heroCdrSecMain: '文殊减 CD 秒数',
  heroCdrSecTransit: '慧殊减 CD 秒数',
  heroBurstDmgMul: '爆发大招伤害倍率',
  heroRangedDmgMul: '暴击大招基础倍率',
  heroPierceMaxMain: '二郎贯穿怪数',
  heroPierceMaxTransit: '牛郎贯穿怪数',
  heroBeamCorridor: '贯穿光束走廊垂直半宽（格）',
  heroDogStunDur: '哮天犬定身时长',
  heroDogTtl: '哮天犬跟随时长',
  heroHealHp: '观音每波回血',
  heroUltFxTtlLong: '大招动画时长·长',
  heroUltFxTtlBite: '大招动画时长·突进',
  heroUltFxTtlSupport: '大招动画时长·辅助',
  heroUltFxTtlDefault: '大招动画时长·默认',
  tangsengHurtImmuneDur: '唐僧受伤免疫时长',
  rangeTolerance: '命中判定半格外扩（格）',
  heroBossFromCount: '引妖王最少英雄数',
  heroBossIntervalMin: '引妖王间隔下界',
  heroBossIntervalMaxBase: '引妖王间隔上界基数',
  heroBossIntervalShrinkCap: '引妖王间隔压缩上限',
  heroBossMaxPerWave: '每波最多引妖王次数',
  waveGapSec: '清波后开下一波等待',

  // 实体字段
  atk: '攻击',
  frq: '攻速',
  rge: '射程',
  targets: '目标数',
  skillCd: '大招 CD（秒）',
  weight: '掉落权重',
  expCostMul: '升阶经验倍率',
  cd: '冷却（秒）',
  cost: '功德价格',
  disabled: '是否下架',
  baseAtk: '基础攻击',
  baseFrq: '基础攻速',
};

export function paramLabel(key: string): string {
  const zh = PARAM_ZH[key];
  return zh ? `${zh}（${key}）` : key;
}

export function paramZh(key: string): string {
  return PARAM_ZH[key] ?? '';
}
