/** 英文配置键 → 中文说明（DevTools 表单 / Diff 展示） */
export const PARAM_ZH: Record<string, string> = {
  // ECONOMY
  INITIAL_PEACH: '开局蟠桃',
  PEACH_PER_KILL: '普通怪掉桃',
  PEACH_PER_BLEED: '唐僧掉血补偿桃',
  PEACH_PER_ELITE: '精英掉桃',
  PEACH_PER_MINI_BOSS: '小 Boss 掉桃',
  PEACH_PER_BOSS: '妖王掉桃',
  TANGSENG_INITIAL_HP: '唐僧初始血量',
  MONSTER_BASE: '每波怪数基数（+波次）',
  PEACH_COST_BASE: '抽卡成本基数',
  PEACH_COST_STEP: '抽卡成本每波递增',
  REMAINING_INTERCEPT: '剩余桃曲线截距',

  // BOARD_POWER
  PRESSURE_RATIO: '承压比下限',
  PRESSURE_RATIO_MAX: '承压比上限',
  PRESSURE_RATIO_FULL_WAVE: '承压比爬满波次',
  PRESSURE_WINDOW_SEC: '承压窗口（秒）',
  PRESSURE_FROM_WAVE: '承压起始波次',
  ENTRANCE_ZONE_LEN: '门口路段长度（格）',
  SPAWN_INTERVAL_MIN: '出怪间隔下限（秒）',
  GATE_WIPE_HP_RATIO: '门口秒杀血量比',
  SPAWN_DIST_JITTER: '同批出怪沿路抖动（格）',
  SPAWN_BATCH_CAP_MAX: '单次出怪批次上限',
  MONSTER_HP_FROM_WAVE: '按武器攻击缩放血量起始波次',
  MONSTER_HP_KILL_SEC: '单怪参考击杀时长（秒）',

  // PLACE_TIMING
  digDur: '挖坑动画时长（秒）',
  dropDur: 'AI 落子动画时长（秒）',
  dragDur: '一键布阵拖拽时长（秒）',
  staggerMin: '连续落子最短间隔（秒）',
  staggerMax: '连续落子最长间隔（秒）',

  // PEACH_TREE
  intervals: '各级产桃间隔（秒）',
  maxLevel: '桃树最高等级',
  plantInterval: '自动种树间隔（秒）',

  // AI_TIMING
  weaponAdjustMin: 'AI 兵器调位间隔下限',
  weaponAdjustMax: 'AI 兵器调位间隔上限',
  partnerAdjustMin: 'AI 配对调位间隔下限',
  partnerAdjustMax: 'AI 配对调位间隔上限',
  adjustFastScale: '快放间隔缩放',

  // GENERAL_TUNING
  CRIT_MULT: '暴击倍率',
  BOND_ATK_BONUS: '羁绊全队攻击加成',

  // WEAPON_TUNING
  rangeStep: '神兵每阶范围加成（格）',
  pctPerTier: '神兵每阶攻/速比例',
  battleFragmentEligibleChance: '本局可掉碎片预排概率',
  heroAttackFragmentChance: '武将攻击触发碎片概率',

  // TUNING · 怪物 / 系统 / 攻击（节选常用）
  monsterSpd: '怪物移速（格/秒）',
  dangerRemaining: '危险提示剩余格数',
  monsterHpBase: '怪物血量基数',
  monsterHpStep: '怪物血量每波递增',
  bossFirstSegLo: '首段妖王波下界',
  bossFirstSegHi: '首段妖王波上界',
  bossFirstSegMin: '首段妖王波最少',
  bossFirstSegMax: '首段妖王波最多',
  bossSegMin: '后续每段妖王波最少',
  bossSegMax: '后续每段妖王波最多',
  bossHpMul: '妖王血量倍率（后期）',
  bossHpMulEarly: '妖王血量倍率（前期）',
  bossSpdMul: '妖王移速倍率',
  bossHpRampWaves: '妖王血量爬升波跨度',
  bossEscortMin: '妖王护卫最少',
  bossEscortMax: '妖王护卫最多',
  bossEscortHpShare: '护卫分血比例',
  bossEscortSpacing: '护卫沿路间距',
  cavalryFromWave: '骑兵波起始波次',
  cavalryWaveChance: '骑兵波概率',
  cavalryRatioBase: '骑兵比例下界',
  cavalryRatioWaveBonusCap: '骑兵比例波次加成上限',
  cavalryRatioWaveDiv: '骑兵比例波次除数',
  cavalryRatioMaxSpread: '骑兵比例随机展宽',
  cavalryRatioCap: '骑兵比例上限',
  cavalrySpdMul: '骑兵移速倍率',
  cavalryHpMul: '骑兵血量倍率',
  lateWaveFrom: '后期堆量起始波',
  lateWaveExtraPerWave: '后期每波额外怪数',
  earlyWaveTo: '前期减量波数',
  earlyWaveReduce: '前期每波多减数量',
  earlyWaveHpStrongTo: '强软血覆盖波次',
  earlyWaveHpStrongMul: '前3波软血倍率',
  earlyWaveHpMul4: '第4波软血',
  earlyWaveHpTo: '软血覆盖波次',
  earlyWaveHpMul: '第5波软血',
  earlyWaveHpMul6: '第6波软血',
  earlyWaveHpMul7: '第7波软血',
  wave1Bonus: '第1波额外怪数',
  minWaveMonsters: '单波怪数下限',
  spawnInterval: '出怪基础间隔（秒）',
  spawnIntervalMin: '出怪间隔下限（秒）',
  summonCostStart: '首次征兵成本',
  summonCostStep: '征兵成本递增',
  summonDraws: '征兵产出数',
  shovelDrawChance: '铲子出现概率',
  shovelPityAfter: '铲子保底次数',
  wordDrawChance: '字牌出现概率',
  wordPityAfter: '字牌保底次数',
  pairPityAfter: '半对保底次数',
  earlyWordCapWave: '前期字牌上限波次',
  earlyWordCap: '前期字牌上限个数',
  earlyWordGuaranteeWave: '前期字牌保底波次',
  earlyWordGuarantee: '前期字牌保底个数',
  earlyShovelWave: '前期铲子配额波次',
  earlyShovelMin: '前期铲子下限',
  earlyShovelMax: '前期铲子上限',
  summonMaxPerKey: '单次同 key 上限',
  summonMaxPerKeyAllOpen: '全开后同 key 上限',
  traySize: '候选区容量',
  initialShovels: '开局铲子数',
  initialOpenSlots: '初始阵位数',
  endlessWavesPerCycle: '无尽每圈波数',
  endlessCycleStep: '无尽每圈强度倍率',
  aiDpsBase: 'AI 拦截 DPS 基数',
  aiDpsPerWave: 'AI 拦截 DPS 每波增量',
  eliteFromWave: '精英出现起始波',
  eliteChance: '精英概率',
  eliteMinGap: '精英最小间隔只数',
  skillRadius: '怪物技能半径（格）',
  skillTargetMin: '技能最少命中兵器',
  skillTargetMax: '技能最多命中兵器',
  skillInterval: '怪物施法间隔（秒）',
  skillFirstDelay: '入场首次施法延迟',
  stunDur: '眩晕时长',
  slowDur: '减速时长',
  slowCooldownMul: '减速冷却倍率',
  weakenDur: '降攻时长',
  weakenAtkMul: '降攻攻击倍率',
  webbindDur: '缠丝时长',
  webbindRangeCut: '缠丝射程削减',
  debuffImmuneDur: '同 debuff 免疫时长',
  miniBossFromWave: '小 Boss 起始波',
  miniBossChance: '小 Boss 概率',
  miniBossHpMul: '小 Boss 血量倍率',
  miniBossSpdMul: '小 Boss 移速倍率',
  miniBossRadius: '小 Boss 光环半径',
  miniBossInterval: '小 Boss 施法间隔',
  miniBossFirstDelay: '小 Boss 首次施法延迟',
  eliteHpMul: '精英血量倍率',
  knockdownDur: '倒下时长',
  hasteDur: '疾风时长',
  hasteSpdMul: '疾风移速倍率',
  healPct: '血泉回复比例',
  aiClearChargeTime: 'AI 清场蓄力秒数',
  aiClearRadius: '清场/紧箍半径',
  aiClearDmgMul: '清场伤害倍率',
  palmPushCells: '神掌击退格数',
  meteorDmgMul: '陨石伤害倍率',
  meteorRadius: '陨石半径',
  meteorPassiveDmgMul: '被动陨石倍率',
  jingguDmgMul: '紧箍咒伤害倍率',
  atkBuffMul: '仙丹攻击倍率',
  frqBuffMul: '风火轮攻速倍率',
  freezeStunDur: '冰封定身时长',
  heroStunDurMain: '满5定身时长',
  heroStunDurTransit: '满3定身时长',
  heroKnockPushMain: '满5击退格数',
  heroKnockPushTransit: '满3击退格数',
  heroStunDmgMul: '定身附带伤害倍率',
  heroChargeStunDmgMul: '冲撞定身伤害倍率',
  heroKnockDmgMul: '击退附带伤害倍率',
  heroSlowDmgMulMain: '满5减速附带伤害',
  heroSlowDmgMulTransit: '满3减速附带伤害',
  heroSlowDur: '武将减速时长',
  heroHealSlowDur: '回复减速时长',
  heroBurnHitMul: '灼烧瞬时倍率',
  heroBurnDpsMul: '灼烧每秒倍率',
  heroBurnDur: '灼烧持续',
  heroBuffAtkMulMain: '老君攻击增益倍率',
  heroBuffAtkMulTransit: '丹君攻击增益倍率',
  heroBuffDurMain: '老君增益时长',
  heroBuffDurTransit: '丹君增益时长',
  heroCdrSecMain: '文殊减 CD 秒数',
  heroCdrSecTransit: '慧殊减 CD 秒数',
  tangsengHurtImmuneDur: '唐僧受伤免疫时长',
  rangeTolerance: '命中半格外扩',
  aiDeployBase: 'AI 每波部署基数',
  aiDeployPerWave: 'AI 每波部署系数',
  aiDeployInterval: 'AI 逐个部署间隔',
  heroBossFromCount: '引妖王最少英雄数',
  heroBossIntervalMin: '引妖王间隔下界',
  heroBossIntervalMaxBase: '引妖王间隔上界基数',
  heroBossIntervalShrinkCap: '引妖王间隔压缩上限',
  heroBossMaxPerWave: '每波最多引妖王次数',
  waveGapSec: '清波后开下一波等待',

  // 实体字段
  atk: '攻击',
  frq: '攻速',
  rge: '射程',
  targets: '目标数',
  skillCd: '大招 CD（秒）',
  weight: '掉落权重',
  expCostMul: '升阶经验倍率',
  cd: '冷却（秒）',
  cost: '功德价格',
  disabled: '是否下架',
  baseAtk: '基础攻击',
  baseFrq: '基础攻速',
};

export function paramLabel(key: string): string {
  const zh = PARAM_ZH[key];
  return zh ? `${zh}（${key}）` : key;
}

export function paramZh(key: string): string {
  return PARAM_ZH[key] ?? '';
}
