// 资源清单的唯一真源：AssetKey → 原始文件名（对应 src/game-assets/ 与 tools/tos-upload.mjs 上传的文件）。
// Web 与微信构建（asset-manifest.web.ts / asset-manifest.wx.ts）先尝试引用 manifest-generated.ts 里的
// 内容哈希 URL（上传时按内容计算），命中则缓存击穿；未命中时回退用本登记的原名拼 bare URL。
// 上传新素材：先跑 `node tools/tos-upload.mjs` 自动生成 manifest-generated.ts，本文件只登记逻辑名→原名，
// 不再手填哈希后缀（哈希由上传时按文件内容计算，同名同内容永远同 URL）。

// 与 tools/tos-upload.mjs 保持一致：火山引擎 TOS（user-growth 桶，公共读），前缀 dev/xy/。
export const CDN_BASE = 'https://user-growth.tos-cn-shanghai.volces.com/dev/xy/';

export const ASSET_FILENAMES: Record<string, string> = {
  tangseng: 'tangseng.png',
  'loading-tangseng': 'loading-tangseng.png',
  'unit-monkey': 'unit-monkey.png',
  'unit-spear': 'unit-spear.png',
  'unit-cavalry': 'unit-cavalry.png',
  'unit-archer': 'unit-archer.png',
  'monster-minion': 'monster-minion.png',
  'monster-boss': 'monster-boss.png',
  'monster-minion-huoyanshan': 'monster-minion-huoyanshan.png',
  'monster-boss-huoyanshan': 'monster-boss-huoyanshan.png',
  'monster-minion-liushahe': 'monster-minion-liushahe.png',
  'monster-boss-liushahe': 'monster-boss-liushahe.png',
  'monster-minion-baiguling': 'monster-minion-baiguling.png',
  'monster-boss-baiguling': 'monster-boss-baiguling.png',
  'monster-minion-pansidong': 'monster-minion-pansidong.png',
  'monster-boss-pansidong': 'monster-boss-pansidong.png',
  'monster-minion-huangfengling': 'monster-minion-huangfengling.png',
  'monster-boss-huangfengling': 'monster-boss-huangfengling.png',
  'monster-cavalry-huoyanshan': 'monster-cavalry-huoyanshan.png',
  'monster-cavalry-liushahe': 'monster-cavalry-liushahe.png',
  'monster-cavalry-baiguling': 'monster-cavalry-baiguling.png',
  'monster-cavalry-pansidong': 'monster-cavalry-pansidong.png',
  'monster-cavalry-huangfengling': 'monster-cavalry-huangfengling.png',
  'monster-miniboss-frost': 'monster-miniboss-frost.png',
  'monster-miniboss-blight': 'monster-miniboss-blight.png',
  'monster-miniboss-quake': 'monster-miniboss-quake.png',
  'monster-miniboss-gale': 'monster-miniboss-gale.png',
  'monster-miniboss-blood': 'monster-miniboss-blood.png',
  'monster-miniboss-lion': 'monster-miniboss-lion.png',
  'item-shovel': 'item-shovel.png',
  'skill-act-bomb': 'skill-act-bomb.png',
  'hero-wukong': 'hero-wukong.png',
  'hero-bajie': 'hero-bajie.png',
  'hero-shaseng': 'hero-shaseng.png',
  'hero-guanyin': 'hero-guanyin.png',
  'hero-nezha': 'hero-nezha.png',
  'hero-erlang': 'hero-erlang.png',
  'hero-ttg': 'hero-ttg.png', // 二郎神大招冲出咬怪的哮天犬（drawErlangDog 用）
  'hero-tangseng-hero': 'hero-tangseng-hero.png',
  'hero-honghaier': 'hero-honghaier.png',
  'hero-tieshan': 'hero-tieshan.png',
  'hero-taibai': 'hero-taibai.png',
  'hero-niumowang': 'hero-niumowang.png',
  'hero-mile': 'hero-mile.png',
  'hero-damang': 'hero-damang.png',
  'hero-niulang': 'hero-niulang.png',
  'hero-jinzha': 'hero-jinzha.png',
  'hero-hongpao': 'hero-hongpao.png',
  'hero-baxian': 'hero-baxian.png',
  'hero-qingniu': 'hero-qingniu.png',
  'hero-tiebei': 'hero-tiebei.png',
  'hero-liusha': 'hero-liusha.png',
  'hero-bailong': 'hero-bailong.png',
  'hero-fanyin': 'hero-fanyin.png',
  'hero-laojun': 'hero-laojun.png',
  'hero-danjun': 'hero-danjun.png',
  'hero-wenshu': 'hero-wenshu.png',
  'hero-huishu': 'hero-huishu.png',
  'map-huoyanshan': 'map-huoyanshan.jpg',
  'map-liushahe': 'map-liushahe.jpg',
  'map-baiguling': 'map-baiguling.jpg',
  'map-pansidong': 'map-pansidong.jpg',
  'map-huangfengling': 'map-huangfengling.jpg',
  'menu-home': 'menu-home.jpg',
  'menu-btn-settings': 'menu-btn-settings.png',
  'menu-btn-codex': 'menu-btn-codex.png',
  'menu-btn-rank': 'menu-btn-rank.png',
  'menu-btn-bag': 'menu-btn-bag.png',
  'menu-btn-start': 'menu-btn-start.png',
  'menu-btn-stamina-plus': 'menu-btn-stamina-plus.png',
  'menu-btn-map': 'menu-btn-map.png',
  'menu-btn-stamina-ad': 'menu-btn-stamina-ad.png',
  'menu-btn-stamina-share': 'menu-btn-stamina-share.png',
  'rank-star-on': 'rank-star-on.png',
  'rank-star-off': 'rank-star-off.png',
  'icon-merit': 'icon-merit.png',
  'icon-stamina': 'icon-stamina.png',
  'skill-act-palm': 'skill-act-palm.png',
  'skill-act-meteor': 'skill-act-meteor.png',
  'skill-act-atk': 'skill-act-atk.png',
  'skill-act-frq': 'skill-act-frq.png',
  'skill-act-freeze': 'skill-act-freeze.png',
  'skill-act-jinggu': 'skill-act-jinggu.png',
  'skill-pas-pantao': 'skill-pas-pantao.png',
  'skill-pas-xiandan': 'skill-pas-xiandan.png',
  'skill-pas-fenghuolun': 'skill-pas-fenghuolun.png',
  'skill-pas-fabaofu': 'skill-pas-fabaofu.png',
  'skill-pas-zhaoxian': 'skill-pas-zhaoxian.png',
  'skill-pas-mojin': 'skill-pas-mojin.png',
  'skill-pas-luoyangchan': 'skill-pas-luoyangchan.png',
  'skill-pas-yunshi': 'skill-pas-yunshi.png',
  'skill-pas-yuni': 'skill-pas-yuni.png',
  'skill-pas-xianyuan': 'skill-pas-xianyuan.png',
  'skill-pas-jubaopen': 'skill-pas-jubaopen.png',
  'skill-pas-hushen': 'skill-pas-hushen.png',
  'skill-pas-zhuwang': 'skill-pas-zhuwang.png',
  'skill-pas-tongxin': 'skill-pas-tongxin.png',
  'skill-pas-dinghai': 'skill-pas-dinghai.png',
  'fence-baiguling': 'fence-baiguling.png',
  'fence-liushahe': 'fence-liushahe.png',
  'fence-pansidong': 'fence-pansidong.png',
  'fence-huangfengling': 'fence-huangfengling.png',
  'gate-liushahe': 'gate-liushahe.png',
  'gate-huangfengling': 'gate-huangfengling.png',
  'merchant-peddler': 'merchant-peddler.png',
  'bgm-pansidong': 'bgm-pansidong.mp3',
  'bgm-menu': 'bgm-menu.mp3',
  'bgm-huoyanshan': 'bgm-huoyanshan.mp3',
  'bgm-baiguling': 'bgm-baiguling.mp3',
  'bgm-liushahe': 'bgm-liushahe.mp3',
};
